### ISSUE TITLE
Image Builder v2 tracker

### ISSUE THREAD

**Issue by Callisto13** [weaveworks-liquidmetal/image-builder#49]
Tracking epic to group steps

Following discussion [here](https://github.com/weaveworks-liquidmetal/image-builder/discussions/35), this is how I am going to proceed:
- [ ] Update the kernel image to only contain the kernel binary https://github.com/weaveworks-liquidmetal/image-builder/issues/31
- [ ] Create a new kernel-mod image containing just the kernel modules https://github.com/weaveworks-liquidmetal/image-builder/issues/31
- [ ] Create a new ubuntu-base image https://github.com/weaveworks-liquidmetal/image-builder/issues/30 from the official CAPI raw image
- [ ] Remove our old ubuntu-base image
- [ ] Update the capmvm-k8s image to build FROM the new ubuntu-base image https://github.com/weaveworks-liquidmetal/image-builder/issues/30
- [ ] Update flintlock to mount in kernel modules as a separate volume https://github.com/weaveworks-liquidmetal/flintlock/issues/537
- [ ] Update capmvm _templates_ to pull in the correct images (capmvm, kernel, modules)
- [ ] Update capmvm to have a nicer UX so people only need to provide an image (capmvm, kernel) version when using the default images https://github.com/weaveworks-liquidmetal/cluster-api-provider-microvm/issues/226
- [ ] Write some docs about all this https://github.com/weaveworks-liquidmetal/image-builder/issues/41
